import pygame as pg
import math

pg.font.init()

RES = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

#FONT
FONT_RPG="Assets\Fonts\AncientModernTales-a7Po.ttf"
FONT_BASIC=pg.font.Font(FONT_RPG,15)
FONT_DEATH=pg.font.Font(FONT_RPG,50)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE=256
HALF_TEXTURE_SIZE=TEXTURE_SIZE//2