import pygame as pg

SCREEN_HEIGHT=900
SCREEN_WIDTH=2*SCREEN_HEIGHT
SCREEN_HALF_WIDTH=SCREEN_WIDTH/2
SCREEN_HALF_HEIGHT=SCREEN_HEIGHT/2
FPS=0

DELTA_TIME=1

DISPLAY=pg.display.set_mode((SCREEN_WIDTH,SCREEN_HEIGHT))
CLOCK=pg.time.Clock()


#MOUSE CONTROL

MOUSE_SENSITIVITY=0.0003
MOUSE_MAX_REL_MOV=40
MOUSE_BORDER_LEFT=100
MOUSE_BORDER_RIGHT=SCREEN_WIDTH-MOUSE_BORDER_LEFT